- configuration:
    config: SCS
    temp: -20
  Fourier: true
  gpu: 1
  checkpoint: -20_SCS_40bar_sorted_fourier_mapping
  dataset:
    sensor_range:
    - -1
    - 40
    data_path: datasets/40_bar.pkl
    test_sensors: 100
    shuffle: false
  logger:
    print_freq: 10000
    save_checkpoint_freq: 10000
  training_settings:
    batch_size: 32
    lr: 0.0085
    epochs: 1500000
    temp_epochs: 3000
    scheduler: MultiStepLR
    gamma: 0.5
    weight_80: 1.0
    weight_25: 1.0
    weight_-20: 1.0
  factor: 160
  train: true
  resume_train: false
  GT_min: -0.0077875
  GT_max: 0.2515
  p_min: -0.36
  p_max: 0.43
  loss_func: MSE
